apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: golang-micro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: Never      # Jangan menarik image dari registry
          ports:
            - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: golang-micro
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP
