apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: golang-micro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never      # Jangan menarik image dari registry
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: golang-micro
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
